name: Flat
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flat.yml
      - process.js
  workflow_dispatch: null
  schedule:
    - cron: 0 8 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v2.x
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://extract-wagtail-gh-pulse.deno.dev
          downloaded_filename: wagtail-metrics.json
          postprocess: process.js
