name: Flat
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch: null
  schedule:
    - cron: "*/30 * * * *"
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v1
        with:
          http_url: https://extract-wagtail-gh-pulse.deno.dev
